### PR TITLE
dont sleep before we even try to get a read lock

### LINKED ISSUE #14107: Node API horrible slow with files_locking
Filing here since not sure if this is an issue in core or the files_locking application, but it's a PRETTY annoying bug anyways…

The following test script creates 100 test files. Without enabled files_locking application the reading of the files requires roughly 400ms, with enabled application it takes more than 5.5 seconds! See https://blackfire.io/profiles/compare/31c8f164-4086-426f-924e-41210fd6197a/graph for a comparison view.

```php
<?php


require_once('./lib/base.php');

$randomFolderName = \OC::$server->getSecureRandom()->getLowStrengthGenerator()->generate(
	5, \OCP\Security\ISecureRandom::CHAR_LOWER
);

\OC_User::createUser($randomFolderName, 'admin');

for ($i = 1; $i <= 100; $i++) {
	mkdir('./data/'.$randomFolderName);
	mkdir('./data/'.$randomFolderName.'/files/');
	mkdir('./data/'.$randomFolderName.'/files/'.$randomFolderName);
	file_put_contents('./data/'.$randomFolderName.'/files/'.$randomFolderName.'/'.$i.'.txt', 'asdf');
}


$time1 = microtime(true);

$view = new \OC\Files\View('/'.$randomFolderName.'/files/');
$files = $view->getDirectoryContent($randomFolderName);

$rootFolder = \OC::$server->getUserFolder($randomFolderName);
$files = $rootFolder->get($randomFolderName)->getDirectoryListing();
foreach($files as $file) {
	if($file->getType() === 'file' && $file->getMimeType() === 'text/plain') {
		$file->getContent();
	}
}

$time2 = microtime(true);
echo "script execution time: ".($time2-$time1);
```
This is a valid use-case and already performed by applications such as the widely used notes app. Reading some small text files should certainly not take that long.

I'm pretty sure we have huge other performance problems as well due to the files_locking application.
 
cc @DeepDiver1975 That's the bug that I referred to in IRC.
cc @icewind1991 Could you take a look at this? THX!

### PR DESCRIPTION
**Pull request by icewind1991**
No need to waste 50ms for every read operation....

Fixes https://github.com/owncloud/core/issues/14107

### CODE REVIEW

**Comment by LukasReschke** [comment]
Works :+1:

Test script goes down from 5.4436509609222 sec to 0.27690482139587 sec

**Comment by PVince81** [comment]
Right, nice catch :+1:

**Comment by PVince81** [comment]
We should probably backport this to OC 8 @karlitschek ?

**Comment by karlitschek** [comment]
yes. please backport :+1:

**Comment by PVince81** [comment]
stable8: https://github.com/owncloud/files_locking/pull/16

**Pull request merged**
