### PR TITLE
Ignore MappedLocal storage, since it doesn't work with the windows locking too well

### LINKED ISSUE #14513: Permissions Denied in MappedLocal.php
@nickvergessen in the forum we already got 12 reports about this issue: https://forum.owncloud.org/viewtopic.php?f=31&t=26421&p=79700

The reports claim that replacing the oC 8 mappedlocal.php with the oC7 one everything will work, there is also some more technical debug stuff happening there.

Would be awesome if you could take a look at this. (might be a duplicate though this issue)

### PR DESCRIPTION
**Pull request by nickvergessen**
Fixes owncloud/core#14513

Should also backport to stable8

@DeepDiver1975 @LukasReschke @icewind1991

### CODE REVIEW

**Comment by icewind1991** [comment]
use `$storage->instanceOfStorage('...')` instead

**Comment by nickvergessen** [comment]
Updated both PRs

**Comment by nickvergessen** [comment]
@icewind1991 would be nice to get this in, before 8.0.1 is out ;)

**Comment by icewind1991** [comment]
:+1: code looks good

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
