### PR TITLE
Fix wrapper setup

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@icewind1991 @schiesbn please review - THX

@jnfrmarks @SergioBertolinSG please retest this change - should fix several issue you reported these days - THX

To be confirmed/evaluated:
Needs to be fixed in stable8 potentially as well

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
fixes https://github.com/owncloud/files_locking/issues/23

**Comment by DeepDiver1975** [comment]
refs owncloud/core#16061
refs owncloud/core#16062

**Comment by DeepDiver1975** [comment]
fixes https://github.com/owncloud/files_locking/issues/17

**Comment by icewind1991** [comment]
Changes look good :+1:

**Comment by SergioBertolinSG** [comment]
Applied the patch to the 8.1 alpha 3 tarball, working fine :+1:  
fixed owncloud/core#16061 and owncloud/core#16062

**Comment by MorrisJobke** [comment]
@DeepDiver1975 There is a ticket for stable8. Should this be backported then?

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Or is #28 the stable8 version of this PR?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Or is #28 the stable8 version of this PR?

yes - but we cannot backport this

**Pull request merged**
